### ISSUE TITLE
Can't use official implementation after Flutter 3.27.1

### ISSUE THREAD

**Issue by khoadng** [wang-bin/fvp#196]
**Describe the bug**
After upgrade to 3.27.1, I can't no longer use official `video_player` implementation.

<details open><summary>Pubspec</summary>

```dart
dependencies:
  flutter:
    sdk: flutter
  fvp: ^0.28.0
  intl: ^0.20.1
  video_player: ^2.9.2
```

</details>

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:video_player/video_player.dart';
import 'package:fvp/fvp.dart' as fvp;

import 'package:logging/logging.dart';
import 'package:intl/intl.dart';

void main() {
  Logger.root.level = Level.ALL;
  final df = DateFormat("HH:mm:ss.SSS");
  Logger.root.onRecord.listen((record) {
    print(
        '${record.loggerName}.${record.level.name}: ${df.format(record.time)}: ${record.message}');
  });

  fvp.registerWith(
    options: {
      'platforms': [
        'linux',
        'windows',
        'macos',
      ],
    },
  );

  runApp(
    const MainApp(),
  );
}

class MainApp extends StatelessWidget {
  const MainApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: Scaffold(
        body: Center(
          child: VideoPlayerWidget(
            videoUrl:
                'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
          ),
        ),
      ),
    );
  }
}

class VideoPlayerWidget extends StatefulWidget {
  final String videoUrl;
  const VideoPlayerWidget({super.key, required this.videoUrl});

  @override
  State<VideoPlayerWidget> createState() => _VideoPlayerWidgetState();
}

class _VideoPlayerWidgetState extends State<VideoPlayerWidget> {
  late VideoPlayerController _controller;
  bool _isPlaying = false;

  @override
  void initState() {
    super.initState();
    _controller = VideoPlayerController.networkUrl(Uri.parse(widget.videoUrl))
      ..initialize().then((_) {
        setState(() {});
      });
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    if (!_controller.value.isInitialized) {
      return const Center(child: CircularProgressIndicator());
    }

    return Column(
      mainAxisAlignment: MainAxisAlignment.center,
      children: [
        AspectRatio(
          aspectRatio: _controller.value.aspectRatio,
          child: VideoPlayer(_controller),
        ),
        Row(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            IconButton(
              icon: Icon(_isPlaying ? Icons.pause : Icons.play_arrow),
              onPressed: () {
                setState(() {
                  _isPlaying = !_isPlaying;
                  _isPlaying ? _controller.play() : _controller.pause();
                });
              },
            ),
            IconButton(
              icon: const Icon(Icons.replay),
              onPressed: () {
                _controller.seekTo(Duration.zero);
              },
            ),
          ],
        ),
      ],
    );
  }
}

```

</details>

**Log (Xiaomi 11 Lite 5G NE, Android 14)**

```
I/flutter (13467): fvp.FINE: 10:40:37.048: registerVideoPlayerPlatformsWith: {platforms: [linux, windows, macos]}
E/LB      (13467): fail to open node: No such file or directory
D/VRI[MainActivity](13467): vri.Setup new sync=wmsSync-VRI[MainActivity]#2
D/OpenGLRenderer(13467): makeCurrent grContext:0xb400007d6601f820 reset mTextureAvailable
D/mple.fontweight(13467): MiuiProcessManagerServiceStub setSchedFifo
I/MiuiProcessManagerImpl(13467): setSchedFifo pid:13467, mode:3
E/flutter (13467): [ERROR:flutter/runtime/dart_vm_initializer.cc(40)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel: "dev.flutter.pigeon.video_player_android.AndroidVideoPlayerApi.initialize"., null, null)
E/flutter (13467): #0      AndroidVideoPlayerApi.initialize (package:video_player_android/src/messages.g.dart:127:7)
E/flutter (13467): <asynchronous suspension>
E/flutter (13467): 
E/flutter (13467): [ERROR:flutter/runtime/dart_vm_initializer.cc(40)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel: "dev.flutter.pigeon.video_player_android.AndroidVideoPlayerApi.create"., null, null)
E/flutter (13467): #0      AndroidVideoPlayerApi.create (package:video_player_android/src/messages.g.dart:151:7)
E/flutter (13467): <asynchronous suspension>
E/flutter (13467): #1      VideoPlayerController.initialize (package:video_player/video_player.dart:440:19)
E/flutter (13467): <asynchronous suspension>
E/flutter (13467): #2      _VideoPlayerWidgetState.initState.<anonymous closure> (package:fontweight/main.dart:66:27)
E/flutter (13467): <asynchronous suspension>
E/flutter (13467): 
```

**Log (iPhone 16 Pro Max simulator)**

```
flutter: fvp.FINE: 10:45:39.262: registerVideoPlayerPlatformsWith: {platforms: [linux, windows, macos]}
[ERROR:flutter/runtime/dart_vm_initializer.cc(40)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel: "dev.flutter.pigeon.video_player_avfoundation.AVFoundationVideoPlayerApi.initialize"., null, null)
#0      AVFoundationVideoPlayerApi.initialize (package:video_player_avfoundation/src/messages.g.dart:127:7)
messages.g.dart:127
<asynchronous suspension>
[ERROR:flutter/runtime/dart_vm_initializer.cc(40)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel: "dev.flutter.pigeon.video_player_avfoundation.AVFoundationVideoPlayerApi.create"., null, null)
#0      AVFoundationVideoPlayerApi.create (package:video_player_avfoundation/src/messages.g.dart:151:7)
messages.g.dart:151
<asynchronous suspension>
#1      VideoPlayerController.initialize (package:video_player/video_player.dart:440:19)
video_player.dart:440
<asynchronous suspension>
#2      _VideoPlayerWidgetState.initState.<anonymous closure> (package:fontweight/main.dart:65:27)
main.dart:65
<asynchronous suspension>
```

**Comment by wang-bin** [comment]
try master branch
