### ISSUE TITLE
Failed to load dynamic library libfvp_plugin.so on Android

### ISSUE THREAD

**Issue by khoadng** [wang-bin/fvp#66]
**Describe the bug**
Throw exception when init on Android

**Source**

```dart
import 'package:flutter/material.dart';
import 'package:video_player/video_player.dart';

import 'package:fvp/fvp.dart' as fvp;
import 'package:logging/logging.dart';
import 'package:intl/intl.dart';

void main() {
  Logger.root.level = Level.ALL;
  final df = DateFormat("HH:mm:ss.SSS");
  Logger.root.onRecord.listen((record) {
    print(
        '${record.loggerName}.${record.level.name}: ${df.format(record.time)}: ${record.message}');
  });
  fvp.registerWith();

  runApp(const MainApp());
}

class MainApp extends StatelessWidget {
  const MainApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: Scaffold(
        body: Center(
          child: Text('Hello World!'),
        ),
      ),
    );
  }
}

```
**Log**
```
I/flutter (25116): fvp.FINE: 18:52:18.908: registerVideoPlayerPlatformsWith: null
E/flutter (25116): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument(s): Failed to load dynamic library 'libfvp_plugin.so': dlopen failed: library "libass.so" not found: needed by /data/app/~~Vw-l8oZcsQf_AYUlmzeo9w==/com.example.test_fvp-kpYmTX0pXYMnQ0wvNzcKXA==/lib/arm64/libfvp_plugin.so in namespace clns-4
E/flutter (25116): #0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:11:43)
E/flutter (25116): #1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:22:12)
E/flutter (25116): #2      Libfvp._load (package:fvp/src/lib.dart:52:29)
E/flutter (25116): #3      Libfvp.instance (package:fvp/src/lib.dart:58:27)
E/flutter (25116): #4      Libfvp.instance (package:fvp/src/lib.dart)
E/flutter (25116): #5      Libfvp.isEmulator (package:fvp/src/lib.dart:80:29)
E/flutter (25116): #6      Libfvp.isEmulator (package:fvp/src/lib.dart)
E/flutter (25116): #7      PlatformEx.isAndroidEmulator (package:fvp/src/extensions.dart:16:19)
E/flutter (25116): #8      MdkVideoPlayerPlatform.registerVideoPlayerPlatformsWith (package:fvp/src/video_player_mdk.dart:138:42)
E/flutter (25116): #9      registerWith (package:fvp/fvp.dart:39:26)
E/flutter (25116): #10     main (package:test_fvp/main.dart:15:7)
E/flutter (25116): #11     _runMain.<anonymous closure> (dart:ui/hooks.dart:301:23)
E/flutter (25116): #12     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
E/flutter (25116): #13     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

**Flutter doctor**
```
[✓] Flutter (Channel stable, 3.16.4, on macOS 13.4.1 22F770820d darwin-arm64, locale en-VN)
    • Flutter version 3.16.4 on channel stable at /Users/khoa/SDK/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2e9cb0aa71 (7 weeks ago), 2023-12-11 14:35:13 -0700
    • Engine revision 54a7145303
    • Dart version 3.2.3
    • DevTools version 2.28.4

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/khoa/Library/Android/sdk
    • Platform android-34, build-tools 33.0.0
    • Java binary at: /Users/khoa/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/223.8836.35.2231.11090377/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.14.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Users/khoa/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/221.6008.13.2211.9619390/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] Android Studio (version 2022.3)
    • Android Studio at /Users/khoa/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/223.8836.35.2231.11090377/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.85.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.80.0

[✓] Connected device (3 available)
    • 2109119DG (mobile) • adb-6b2da568-RvlFYv._adb-tls-connect._tcp. • android-arm64  • Android 13 (API 33)
    • macOS (desktop)    • macos                                      • darwin-arm64   • macOS 13.4.1 22F770820d darwin-arm64
    • Chrome (web)       • chrome                                     • web-javascript • Google Chrome 121.0.6167.85

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

**Other**
fvp: ^0.13.1

**Comment by wang-bin** [comment]
Please rebuild your project and paste the entire build log here

**Comment by khoadng** [comment]
The entire build log using `flutter run --verbose`` is extremely long for some reason. I can't even paste it here
It is just a simple project created with ```flutter create```

**Comment by khoadng** [comment]
[logs.txt](https://github.com/wang-bin/fvp/files/14071217/logs.txt)

**Comment by wang-bin** [comment]
I used a cmake feature not supported in old versions. run `flutter clean` and build again should fix the issue

**Comment by khoadng** [comment]
Sill a same issue after running `flutter clean`

**Comment by wang-bin** [comment]
i need the build log

**Comment by khoadng** [comment]
Here is the new log

[logs.txt](https://github.com/wang-bin/fvp/files/14074686/logs.txt)

**Comment by wang-bin** [comment]
still using cached files. `rm -rf ~/.pub-cache/hosted/pub.dev/fvp-0.13.1/android/{.cxx,mdk-sdk*}` then run again

**Comment by khoadng** [comment]
it works, thanks
